version: '3.8'

services:
  rasa:
    build:
      context: .
      dockerfile: Dockerfile.rasa
    ports:
      - "5005:5005"
    environment:
      - PORT=5005
    command: run --enable-api --cors "*" --port 5005

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - RASA_URL=http://rasa:5005
    depends_on:
      - rasa

  actions:
    build: .
    ports:
      - "5055:5055"
    command: rasa run actions --port 5055
    restart: always 