[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.rasa"

[deploy]
startCommand = "rasa run --enable-api --cors '*' --debug"
healthcheckPath = "/version"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PORT = "5005"

[[services]]
name = "web"
dockerfilePath = "Dockerfile"
startCommand = "python serve_test_widget.py"
port = 3000
healthcheckPath = "/"
healthcheckTimeout = 300
envs = { RASA_URL = "${{RAILWAY_SERVICE_RASA_URL}}" } 